//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class id_list {
    
    private int[] idsField;
    
    private long next_cursorField;
    
    private sbyte previous_cursorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("id", IsNullable=false)]
    public int[] ids {
        get {
            return this.idsField;
        }
        set {
            this.idsField = value;
        }
    }
    
    /// <remarks/>
    public long next_cursor {
        get {
            return this.next_cursorField;
        }
        set {
            this.next_cursorField = value;
        }
    }
    
    /// <remarks/>
    public sbyte previous_cursor {
        get {
            return this.previous_cursorField;
        }
        set {
            this.previous_cursorField = value;
        }
    }
}
