//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class user {
    
    private int idField;
    
    private string nameField;
    
    private string screen_nameField;
    
    private string locationField;
    
    private string profile_image_urlField;
    
    private string profile_image_url_httpsField;
    
    private string urlField;
    
    private string descriptionField;
    
    private string protectedField;
    
    private int followers_countField;
    
    private string profile_background_colorField;
    
    private int profile_text_colorField;
    
    private string profile_link_colorField;
    
    private string profile_sidebar_fill_colorField;
    
    private string profile_sidebar_border_colorField;
    
    private int friends_countField;
    
    private string created_atField;
    
    private int favourites_countField;
    
    private short utc_offsetField;
    
    private string time_zoneField;
    
    private string profile_background_image_urlField;
    
    private string profile_background_image_url_httpsField;
    
    private string profile_background_tileField;
    
    private string profile_use_background_imageField;
    
    private string geo_enabledField;
    
    private string verifiedField;
    
    private short statuses_countField;
    
    private string langField;
    
    private string contributors_enabledField;
    
    private string is_translatorField;
    
    private short listed_countField;
    
    private string default_profileField;
    
    private string default_profile_imageField;
    
    private string followingField;
    
    private string follow_request_sentField;
    
    private string notificationsField;
    
    private userStatus statusField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string screen_name {
        get {
            return this.screen_nameField;
        }
        set {
            this.screen_nameField = value;
        }
    }
    
    /// <remarks/>
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string profile_image_url {
        get {
            return this.profile_image_urlField;
        }
        set {
            this.profile_image_urlField = value;
        }
    }
    
    /// <remarks/>
    public string profile_image_url_https {
        get {
            return this.profile_image_url_httpsField;
        }
        set {
            this.profile_image_url_httpsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string @protected {
        get {
            return this.protectedField;
        }
        set {
            this.protectedField = value;
        }
    }
    
    /// <remarks/>
    public int followers_count {
        get {
            return this.followers_countField;
        }
        set {
            this.followers_countField = value;
        }
    }
    
    /// <remarks/>
    public string profile_background_color {
        get {
            return this.profile_background_colorField;
        }
        set {
            this.profile_background_colorField = value;
        }
    }
    
    /// <remarks/>
    public int profile_text_color {
        get {
            return this.profile_text_colorField;
        }
        set {
            this.profile_text_colorField = value;
        }
    }
    
    /// <remarks/>
    public string profile_link_color {
        get {
            return this.profile_link_colorField;
        }
        set {
            this.profile_link_colorField = value;
        }
    }
    
    /// <remarks/>
    public string profile_sidebar_fill_color {
        get {
            return this.profile_sidebar_fill_colorField;
        }
        set {
            this.profile_sidebar_fill_colorField = value;
        }
    }
    
    /// <remarks/>
    public string profile_sidebar_border_color {
        get {
            return this.profile_sidebar_border_colorField;
        }
        set {
            this.profile_sidebar_border_colorField = value;
        }
    }
    
    /// <remarks/>
    public int friends_count {
        get {
            return this.friends_countField;
        }
        set {
            this.friends_countField = value;
        }
    }
    
    /// <remarks/>
    public string created_at {
        get {
            return this.created_atField;
        }
        set {
            this.created_atField = value;
        }
    }
    
    /// <remarks/>
    public int favourites_count {
        get {
            return this.favourites_countField;
        }
        set {
            this.favourites_countField = value;
        }
    }
    
    /// <remarks/>
    public short utc_offset {
        get {
            return this.utc_offsetField;
        }
        set {
            this.utc_offsetField = value;
        }
    }
    
    /// <remarks/>
    public string time_zone {
        get {
            return this.time_zoneField;
        }
        set {
            this.time_zoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string profile_background_image_url {
        get {
            return this.profile_background_image_urlField;
        }
        set {
            this.profile_background_image_urlField = value;
        }
    }
    
    /// <remarks/>
    public string profile_background_image_url_https {
        get {
            return this.profile_background_image_url_httpsField;
        }
        set {
            this.profile_background_image_url_httpsField = value;
        }
    }
    
    /// <remarks/>
    public string profile_background_tile {
        get {
            return this.profile_background_tileField;
        }
        set {
            this.profile_background_tileField = value;
        }
    }
    
    /// <remarks/>
    public string profile_use_background_image {
        get {
            return this.profile_use_background_imageField;
        }
        set {
            this.profile_use_background_imageField = value;
        }
    }
    
    /// <remarks/>
    public string geo_enabled {
        get {
            return this.geo_enabledField;
        }
        set {
            this.geo_enabledField = value;
        }
    }
    
    /// <remarks/>
    public string verified {
        get {
            return this.verifiedField;
        }
        set {
            this.verifiedField = value;
        }
    }
    
    /// <remarks/>
    public short statuses_count {
        get {
            return this.statuses_countField;
        }
        set {
            this.statuses_countField = value;
        }
    }
    
    /// <remarks/>
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    public string contributors_enabled {
        get {
            return this.contributors_enabledField;
        }
        set {
            this.contributors_enabledField = value;
        }
    }
    
    /// <remarks/>
    public string is_translator {
        get {
            return this.is_translatorField;
        }
        set {
            this.is_translatorField = value;
        }
    }
    
    /// <remarks/>
    public short listed_count {
        get {
            return this.listed_countField;
        }
        set {
            this.listed_countField = value;
        }
    }
    
    /// <remarks/>
    public string default_profile {
        get {
            return this.default_profileField;
        }
        set {
            this.default_profileField = value;
        }
    }
    
    /// <remarks/>
    public string default_profile_image {
        get {
            return this.default_profile_imageField;
        }
        set {
            this.default_profile_imageField = value;
        }
    }
    
    /// <remarks/>
    public string following {
        get {
            return this.followingField;
        }
        set {
            this.followingField = value;
        }
    }
    
    /// <remarks/>
    public string follow_request_sent {
        get {
            return this.follow_request_sentField;
        }
        set {
            this.follow_request_sentField = value;
        }
    }
    
    /// <remarks/>
    public string notifications {
        get {
            return this.notificationsField;
        }
        set {
            this.notificationsField = value;
        }
    }
    
    /// <remarks/>
    public userStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class userStatus {
    
    private string created_atField;
    
    private long idField;
    
    private string textField;
    
    private string sourceField;
    
    private string truncatedField;
    
    private string in_reply_to_status_idField;
    
    private string in_reply_to_user_idField;
    
    private string in_reply_to_screen_nameField;
    
    private string geoField;
    
    private string coordinatesField;
    
    private string placeField;
    
    private string contributorsField;
    
    private sbyte retweet_countField;
    
    private sbyte favorite_countField;
    
    private string favoritedField;
    
    private string retweetedField;
    
    private userStatusEntities entitiesField;
    
    /// <remarks/>
    public string created_at {
        get {
            return this.created_atField;
        }
        set {
            this.created_atField = value;
        }
    }
    
    /// <remarks/>
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string truncated {
        get {
            return this.truncatedField;
        }
        set {
            this.truncatedField = value;
        }
    }
    
    /// <remarks/>
    public string in_reply_to_status_id {
        get {
            return this.in_reply_to_status_idField;
        }
        set {
            this.in_reply_to_status_idField = value;
        }
    }
    
    /// <remarks/>
    public string in_reply_to_user_id {
        get {
            return this.in_reply_to_user_idField;
        }
        set {
            this.in_reply_to_user_idField = value;
        }
    }
    
    /// <remarks/>
    public string in_reply_to_screen_name {
        get {
            return this.in_reply_to_screen_nameField;
        }
        set {
            this.in_reply_to_screen_nameField = value;
        }
    }
    
    /// <remarks/>
    public string geo {
        get {
            return this.geoField;
        }
        set {
            this.geoField = value;
        }
    }
    
    /// <remarks/>
    public string coordinates {
        get {
            return this.coordinatesField;
        }
        set {
            this.coordinatesField = value;
        }
    }
    
    /// <remarks/>
    public string place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
    
    /// <remarks/>
    public string contributors {
        get {
            return this.contributorsField;
        }
        set {
            this.contributorsField = value;
        }
    }
    
    /// <remarks/>
    public sbyte retweet_count {
        get {
            return this.retweet_countField;
        }
        set {
            this.retweet_countField = value;
        }
    }
    
    /// <remarks/>
    public sbyte favorite_count {
        get {
            return this.favorite_countField;
        }
        set {
            this.favorite_countField = value;
        }
    }
    
    /// <remarks/>
    public string favorited {
        get {
            return this.favoritedField;
        }
        set {
            this.favoritedField = value;
        }
    }
    
    /// <remarks/>
    public string retweeted {
        get {
            return this.retweetedField;
        }
        set {
            this.retweetedField = value;
        }
    }
    
    /// <remarks/>
    //public userStatusEntities entities {
    //    get {
    //        return this.entitiesField;
    //    }
    //    set {
    //        this.entitiesField = value;
    //    }
    //}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class userStatusEntities {
    
    private userStatusEntitiesUser_mentions user_mentionsField;
    
    private string urlsField;
    
    private string hashtagsField;
    
    /// <remarks/>
    public userStatusEntitiesUser_mentions user_mentions {
        get {
            return this.user_mentionsField;
        }
        set {
            this.user_mentionsField = value;
        }
    }
    
    /// <remarks/>
    public string urls {
        get {
            return this.urlsField;
        }
        set {
            this.urlsField = value;
        }
    }
    
    /// <remarks/>
    public string hashtags {
        get {
            return this.hashtagsField;
        }
        set {
            this.hashtagsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class userStatusEntitiesUser_mentions {
    
    private userStatusEntitiesUser_mentionsUser_mention user_mentionField;
    
    /// <remarks/>
    public userStatusEntitiesUser_mentionsUser_mention user_mention {
        get {
            return this.user_mentionField;
        }
        set {
            this.user_mentionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class userStatusEntitiesUser_mentionsUser_mention {
    
    private string screen_nameField;
    
    private string nameField;
    
    private int idField;
    
    private sbyte startField;
    
    private bool startFieldSpecified;
    
    private sbyte endField;
    
    private bool endFieldSpecified;
    
    /// <remarks/>
    public string screen_name {
        get {
            return this.screen_nameField;
        }
        set {
            this.screen_nameField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startSpecified {
        get {
            return this.startFieldSpecified;
        }
        set {
            this.startFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endSpecified {
        get {
            return this.endFieldSpecified;
        }
        set {
            this.endFieldSpecified = value;
        }
    }
}
