//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class users {
    
    private usersUser[] userField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("user")]
    public usersUser[] user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUser {
    
    private int idField;
    
    private string nameField;
    
    private string screen_nameField;
    
    private string locationField;
    
    private string descriptionField;
    
    private string profile_image_urlField;
    
    private string profile_image_url_httpsField;
    
    private string urlField;
    
    private string protectedField;
    
    private int followers_countField;
    
    private string profile_background_colorField;
    
    private int profile_text_colorField;
    
    private string profile_link_colorField;
    
    private string profile_sidebar_fill_colorField;
    
    private string profile_sidebar_border_colorField;
    
    private int friends_countField;
    
    private string created_atField;
    
    private int favourites_countField;
    
    private short utc_offsetField;
    
    private string time_zoneField;
    
    private string profile_background_image_urlField;
    
    private string profile_background_image_url_httpsField;
    
    private string profile_background_tileField;
    
    private string profile_use_background_imageField;
    
    private string notificationsField;
    
    private string geo_enabledField;
    
    private string verifiedField;
    
    private string followingField;
    
    private short statuses_countField;
    
    private string langField;
    
    private string contributors_enabledField;
    
    private string follow_request_sentField;
    
    private int listed_countField;
    
    private string default_profileField;
    
    private string default_profile_imageField;
    
    private string is_translatorField;
    
    private usersUserStatus statusField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string screen_name {
        get {
            return this.screen_nameField;
        }
        set {
            this.screen_nameField = value;
        }
    }
    
    /// <remarks/>
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string profile_image_url {
        get {
            return this.profile_image_urlField;
        }
        set {
            this.profile_image_urlField = value;
        }
    }
    
    /// <remarks/>
    public string profile_image_url_https {
        get {
            return this.profile_image_url_httpsField;
        }
        set {
            this.profile_image_url_httpsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    public string @protected {
        get {
            return this.protectedField;
        }
        set {
            this.protectedField = value;
        }
    }
    
    /// <remarks/>
    public int followers_count {
        get {
            return this.followers_countField;
        }
        set {
            this.followers_countField = value;
        }
    }
    
    /// <remarks/>
    public string profile_background_color {
        get {
            return this.profile_background_colorField;
        }
        set {
            this.profile_background_colorField = value;
        }
    }
    
    /// <remarks/>
    public int profile_text_color {
        get {
            return this.profile_text_colorField;
        }
        set {
            this.profile_text_colorField = value;
        }
    }
    
    /// <remarks/>
    public string profile_link_color {
        get {
            return this.profile_link_colorField;
        }
        set {
            this.profile_link_colorField = value;
        }
    }
    
    /// <remarks/>
    public string profile_sidebar_fill_color {
        get {
            return this.profile_sidebar_fill_colorField;
        }
        set {
            this.profile_sidebar_fill_colorField = value;
        }
    }
    
    /// <remarks/>
    public string profile_sidebar_border_color {
        get {
            return this.profile_sidebar_border_colorField;
        }
        set {
            this.profile_sidebar_border_colorField = value;
        }
    }
    
    /// <remarks/>
    public int friends_count {
        get {
            return this.friends_countField;
        }
        set {
            this.friends_countField = value;
        }
    }
    
    /// <remarks/>
    public string created_at {
        get {
            return this.created_atField;
        }
        set {
            this.created_atField = value;
        }
    }
    
    /// <remarks/>
    public int favourites_count {
        get {
            return this.favourites_countField;
        }
        set {
            this.favourites_countField = value;
        }
    }
    
    /// <remarks/>
    public short utc_offset {
        get {
            return this.utc_offsetField;
        }
        set {
            this.utc_offsetField = value;
        }
    }
    
    /// <remarks/>
    public string time_zone {
        get {
            return this.time_zoneField;
        }
        set {
            this.time_zoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string profile_background_image_url {
        get {
            return this.profile_background_image_urlField;
        }
        set {
            this.profile_background_image_urlField = value;
        }
    }
    
    /// <remarks/>
    public string profile_background_image_url_https {
        get {
            return this.profile_background_image_url_httpsField;
        }
        set {
            this.profile_background_image_url_httpsField = value;
        }
    }
    
    /// <remarks/>
    public string profile_background_tile {
        get {
            return this.profile_background_tileField;
        }
        set {
            this.profile_background_tileField = value;
        }
    }
    
    /// <remarks/>
    public string profile_use_background_image {
        get {
            return this.profile_use_background_imageField;
        }
        set {
            this.profile_use_background_imageField = value;
        }
    }
    
    /// <remarks/>
    public string notifications {
        get {
            return this.notificationsField;
        }
        set {
            this.notificationsField = value;
        }
    }
    
    /// <remarks/>
    public string geo_enabled {
        get {
            return this.geo_enabledField;
        }
        set {
            this.geo_enabledField = value;
        }
    }
    
    /// <remarks/>
    public string verified {
        get {
            return this.verifiedField;
        }
        set {
            this.verifiedField = value;
        }
    }
    
    /// <remarks/>
    public string following {
        get {
            return this.followingField;
        }
        set {
            this.followingField = value;
        }
    }
    
    /// <remarks/>
    public short statuses_count {
        get {
            return this.statuses_countField;
        }
        set {
            this.statuses_countField = value;
        }
    }
    
    /// <remarks/>
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    public string contributors_enabled {
        get {
            return this.contributors_enabledField;
        }
        set {
            this.contributors_enabledField = value;
        }
    }
    
    /// <remarks/>
    public string follow_request_sent {
        get {
            return this.follow_request_sentField;
        }
        set {
            this.follow_request_sentField = value;
        }
    }
    
    /// <remarks/>
    public int listed_count {
        get {
            return this.listed_countField;
        }
        set {
            this.listed_countField = value;
        }
    }
    
    /// <remarks/>
    public string default_profile {
        get {
            return this.default_profileField;
        }
        set {
            this.default_profileField = value;
        }
    }
    
    /// <remarks/>
    public string default_profile_image {
        get {
            return this.default_profile_imageField;
        }
        set {
            this.default_profile_imageField = value;
        }
    }
    
    /// <remarks/>
    public string is_translator {
        get {
            return this.is_translatorField;
        }
        set {
            this.is_translatorField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatus {
    
    private string created_atField;
    
    private long idField;
    
    private string textField;
    
    private string sourceField;
    
    private string truncatedField;
    
    private string favoritedField;
    
    private string in_reply_to_status_idField;
    
    private string in_reply_to_user_idField;
    
    private string in_reply_to_screen_nameField;
    
    private short retweet_countField;
    
    private string retweetedField;
    
    private usersUserStatusRetweeted_status retweeted_statusField;
    
    private string geoField;
    
    private string coordinatesField;
    
    private string placeField;
    
    private string possibly_sensitiveField;
    
    private string contributorsField;
    
    private usersUserStatusEntities entitiesField;
    
    /// <remarks/>
    public string created_at {
        get {
            return this.created_atField;
        }
        set {
            this.created_atField = value;
        }
    }
    
    /// <remarks/>
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string truncated {
        get {
            return this.truncatedField;
        }
        set {
            this.truncatedField = value;
        }
    }
    
    /// <remarks/>
    public string favorited {
        get {
            return this.favoritedField;
        }
        set {
            this.favoritedField = value;
        }
    }
    
    /// <remarks/>
    public string in_reply_to_status_id {
        get {
            return this.in_reply_to_status_idField;
        }
        set {
            this.in_reply_to_status_idField = value;
        }
    }
    
    /// <remarks/>
    public string in_reply_to_user_id {
        get {
            return this.in_reply_to_user_idField;
        }
        set {
            this.in_reply_to_user_idField = value;
        }
    }
    
    /// <remarks/>
    public string in_reply_to_screen_name {
        get {
            return this.in_reply_to_screen_nameField;
        }
        set {
            this.in_reply_to_screen_nameField = value;
        }
    }
    
    /// <remarks/>
    public short retweet_count {
        get {
            return this.retweet_countField;
        }
        set {
            this.retweet_countField = value;
        }
    }
    
    /// <remarks/>
    public string retweeted {
        get {
            return this.retweetedField;
        }
        set {
            this.retweetedField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusRetweeted_status retweeted_status {
        get {
            return this.retweeted_statusField;
        }
        set {
            this.retweeted_statusField = value;
        }
    }
    
    /// <remarks/>
    public string geo {
        get {
            return this.geoField;
        }
        set {
            this.geoField = value;
        }
    }
    
    /// <remarks/>
    public string coordinates {
        get {
            return this.coordinatesField;
        }
        set {
            this.coordinatesField = value;
        }
    }
    
    /// <remarks/>
    public string place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
    
    /// <remarks/>
    public string possibly_sensitive {
        get {
            return this.possibly_sensitiveField;
        }
        set {
            this.possibly_sensitiveField = value;
        }
    }
    
    /// <remarks/>
    public string contributors {
        get {
            return this.contributorsField;
        }
        set {
            this.contributorsField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusEntities entities {
        get {
            return this.entitiesField;
        }
        set {
            this.entitiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_status {
    
    private string created_atField;
    
    private long idField;
    
    private string textField;
    
    private string sourceField;
    
    private string truncatedField;
    
    private string favoritedField;
    
    private string in_reply_to_status_idField;
    
    private string in_reply_to_user_idField;
    
    private string in_reply_to_screen_nameField;
    
    private short retweet_countField;
    
    private string retweetedField;
    
    private string geoField;
    
    private string coordinatesField;
    
    private string placeField;
    
    private string possibly_sensitiveField;
    
    private string contributorsField;
    
    private usersUserStatusRetweeted_statusEntities entitiesField;
    
    /// <remarks/>
    public string created_at {
        get {
            return this.created_atField;
        }
        set {
            this.created_atField = value;
        }
    }
    
    /// <remarks/>
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string truncated {
        get {
            return this.truncatedField;
        }
        set {
            this.truncatedField = value;
        }
    }
    
    /// <remarks/>
    public string favorited {
        get {
            return this.favoritedField;
        }
        set {
            this.favoritedField = value;
        }
    }
    
    /// <remarks/>
    public string in_reply_to_status_id {
        get {
            return this.in_reply_to_status_idField;
        }
        set {
            this.in_reply_to_status_idField = value;
        }
    }
    
    /// <remarks/>
    public string in_reply_to_user_id {
        get {
            return this.in_reply_to_user_idField;
        }
        set {
            this.in_reply_to_user_idField = value;
        }
    }
    
    /// <remarks/>
    public string in_reply_to_screen_name {
        get {
            return this.in_reply_to_screen_nameField;
        }
        set {
            this.in_reply_to_screen_nameField = value;
        }
    }
    
    /// <remarks/>
    public short retweet_count {
        get {
            return this.retweet_countField;
        }
        set {
            this.retweet_countField = value;
        }
    }
    
    /// <remarks/>
    public string retweeted {
        get {
            return this.retweetedField;
        }
        set {
            this.retweetedField = value;
        }
    }
    
    /// <remarks/>
    public string geo {
        get {
            return this.geoField;
        }
        set {
            this.geoField = value;
        }
    }
    
    /// <remarks/>
    public string coordinates {
        get {
            return this.coordinatesField;
        }
        set {
            this.coordinatesField = value;
        }
    }
    
    /// <remarks/>
    public string place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
    
    /// <remarks/>
    public string possibly_sensitive {
        get {
            return this.possibly_sensitiveField;
        }
        set {
            this.possibly_sensitiveField = value;
        }
    }
    
    /// <remarks/>
    public string contributors {
        get {
            return this.contributorsField;
        }
        set {
            this.contributorsField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusRetweeted_statusEntities entities {
        get {
            return this.entitiesField;
        }
        set {
            this.entitiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_statusEntities {
    
    private string user_mentionsField;
    
    private usersUserStatusRetweeted_statusEntitiesUrls urlsField;
    
    private usersUserStatusRetweeted_statusEntitiesMedia mediaField;
    
    private string hashtagsField;
    
    /// <remarks/>
    public string user_mentions {
        get {
            return this.user_mentionsField;
        }
        set {
            this.user_mentionsField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusRetweeted_statusEntitiesUrls urls {
        get {
            return this.urlsField;
        }
        set {
            this.urlsField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusRetweeted_statusEntitiesMedia media {
        get {
            return this.mediaField;
        }
        set {
            this.mediaField = value;
        }
    }
    
    /// <remarks/>
    public string hashtags {
        get {
            return this.hashtagsField;
        }
        set {
            this.hashtagsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_statusEntitiesUrls {
    
    private usersUserStatusRetweeted_statusEntitiesUrlsUrl urlField;
    
    /// <remarks/>
    public usersUserStatusRetweeted_statusEntitiesUrlsUrl url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_statusEntitiesUrlsUrl {
    
    private string urlField;
    
    private string display_urlField;
    
    private string expanded_urlField;
    
    private sbyte endField;
    
    private bool endFieldSpecified;
    
    private sbyte startField;
    
    private bool startFieldSpecified;
    
    /// <remarks/>
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    public string display_url {
        get {
            return this.display_urlField;
        }
        set {
            this.display_urlField = value;
        }
    }
    
    /// <remarks/>
    public string expanded_url {
        get {
            return this.expanded_urlField;
        }
        set {
            this.expanded_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endSpecified {
        get {
            return this.endFieldSpecified;
        }
        set {
            this.endFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startSpecified {
        get {
            return this.startFieldSpecified;
        }
        set {
            this.startFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_statusEntitiesMedia {
    
    private usersUserStatusRetweeted_statusEntitiesMediaCreative creativeField;
    
    /// <remarks/>
    public usersUserStatusRetweeted_statusEntitiesMediaCreative creative {
        get {
            return this.creativeField;
        }
        set {
            this.creativeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_statusEntitiesMediaCreative {
    
    private string typeField;
    
    private string urlField;
    
    private string media_urlField;
    
    private string media_url_httpsField;
    
    private string display_urlField;
    
    private long id_strField;
    
    private string expanded_urlField;
    
    private usersUserStatusRetweeted_statusEntitiesMediaCreativeSizes sizesField;
    
    private long idField;
    
    private sbyte endField;
    
    private bool endFieldSpecified;
    
    private sbyte startField;
    
    private bool startFieldSpecified;
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string media_url {
        get {
            return this.media_urlField;
        }
        set {
            this.media_urlField = value;
        }
    }
    
    /// <remarks/>
    public string media_url_https {
        get {
            return this.media_url_httpsField;
        }
        set {
            this.media_url_httpsField = value;
        }
    }
    
    /// <remarks/>
    public string display_url {
        get {
            return this.display_urlField;
        }
        set {
            this.display_urlField = value;
        }
    }
    
    /// <remarks/>
    public long id_str {
        get {
            return this.id_strField;
        }
        set {
            this.id_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string expanded_url {
        get {
            return this.expanded_urlField;
        }
        set {
            this.expanded_urlField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusRetweeted_statusEntitiesMediaCreativeSizes sizes {
        get {
            return this.sizesField;
        }
        set {
            this.sizesField = value;
        }
    }
    
    /// <remarks/>
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endSpecified {
        get {
            return this.endFieldSpecified;
        }
        set {
            this.endFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startSpecified {
        get {
            return this.startFieldSpecified;
        }
        set {
            this.startFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_statusEntitiesMediaCreativeSizes {
    
    private usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesLarge largeField;
    
    private usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesSmall smallField;
    
    private usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesMedium mediumField;
    
    private usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesThumb thumbField;
    
    /// <remarks/>
    public usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesLarge large {
        get {
            return this.largeField;
        }
        set {
            this.largeField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesSmall small {
        get {
            return this.smallField;
        }
        set {
            this.smallField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesMedium medium {
        get {
            return this.mediumField;
        }
        set {
            this.mediumField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesThumb thumb {
        get {
            return this.thumbField;
        }
        set {
            this.thumbField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesLarge {
    
    private short wField;
    
    private short hField;
    
    private string resizeField;
    
    /// <remarks/>
    public short w {
        get {
            return this.wField;
        }
        set {
            this.wField = value;
        }
    }
    
    /// <remarks/>
    public short h {
        get {
            return this.hField;
        }
        set {
            this.hField = value;
        }
    }
    
    /// <remarks/>
    public string resize {
        get {
            return this.resizeField;
        }
        set {
            this.resizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesSmall {
    
    private short wField;
    
    private short hField;
    
    private string resizeField;
    
    /// <remarks/>
    public short w {
        get {
            return this.wField;
        }
        set {
            this.wField = value;
        }
    }
    
    /// <remarks/>
    public short h {
        get {
            return this.hField;
        }
        set {
            this.hField = value;
        }
    }
    
    /// <remarks/>
    public string resize {
        get {
            return this.resizeField;
        }
        set {
            this.resizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesMedium {
    
    private short wField;
    
    private short hField;
    
    private string resizeField;
    
    /// <remarks/>
    public short w {
        get {
            return this.wField;
        }
        set {
            this.wField = value;
        }
    }
    
    /// <remarks/>
    public short h {
        get {
            return this.hField;
        }
        set {
            this.hField = value;
        }
    }
    
    /// <remarks/>
    public string resize {
        get {
            return this.resizeField;
        }
        set {
            this.resizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusRetweeted_statusEntitiesMediaCreativeSizesThumb {
    
    private short wField;
    
    private short hField;
    
    private string resizeField;
    
    /// <remarks/>
    public short w {
        get {
            return this.wField;
        }
        set {
            this.wField = value;
        }
    }
    
    /// <remarks/>
    public short h {
        get {
            return this.hField;
        }
        set {
            this.hField = value;
        }
    }
    
    /// <remarks/>
    public string resize {
        get {
            return this.resizeField;
        }
        set {
            this.resizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntities {
    
    private usersUserStatusEntitiesUser_mentions user_mentionsField;
    
    private usersUserStatusEntitiesUrls urlsField;
    
    private usersUserStatusEntitiesMedia mediaField;
    
    private string hashtagsField;
    
    /// <remarks/>
    public usersUserStatusEntitiesUser_mentions user_mentions {
        get {
            return this.user_mentionsField;
        }
        set {
            this.user_mentionsField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusEntitiesUrls urls {
        get {
            return this.urlsField;
        }
        set {
            this.urlsField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusEntitiesMedia media {
        get {
            return this.mediaField;
        }
        set {
            this.mediaField = value;
        }
    }
    
    /// <remarks/>
    public string hashtags {
        get {
            return this.hashtagsField;
        }
        set {
            this.hashtagsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesUser_mentions {
    
    private usersUserStatusEntitiesUser_mentionsUser_mention user_mentionField;
    
    /// <remarks/>
    public usersUserStatusEntitiesUser_mentionsUser_mention user_mention {
        get {
            return this.user_mentionField;
        }
        set {
            this.user_mentionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesUser_mentionsUser_mention {
    
    private int idField;
    
    private string screen_nameField;
    
    private string nameField;
    
    private sbyte endField;
    
    private bool endFieldSpecified;
    
    private sbyte startField;
    
    private bool startFieldSpecified;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string screen_name {
        get {
            return this.screen_nameField;
        }
        set {
            this.screen_nameField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endSpecified {
        get {
            return this.endFieldSpecified;
        }
        set {
            this.endFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startSpecified {
        get {
            return this.startFieldSpecified;
        }
        set {
            this.startFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesUrls {
    
    private usersUserStatusEntitiesUrlsUrl urlField;
    
    private string[] textField;
    
    /// <remarks/>
    public usersUserStatusEntitiesUrlsUrl url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesUrlsUrl {
    
    private string urlField;
    
    private string display_urlField;
    
    private string expanded_urlField;
    
    private sbyte endField;
    
    private bool endFieldSpecified;
    
    private sbyte startField;
    
    private bool startFieldSpecified;
    
    /// <remarks/>
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    public string display_url {
        get {
            return this.display_urlField;
        }
        set {
            this.display_urlField = value;
        }
    }
    
    /// <remarks/>
    public string expanded_url {
        get {
            return this.expanded_urlField;
        }
        set {
            this.expanded_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endSpecified {
        get {
            return this.endFieldSpecified;
        }
        set {
            this.endFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startSpecified {
        get {
            return this.startFieldSpecified;
        }
        set {
            this.startFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesMedia {
    
    private usersUserStatusEntitiesMediaCreative creativeField;
    
    /// <remarks/>
    public usersUserStatusEntitiesMediaCreative creative {
        get {
            return this.creativeField;
        }
        set {
            this.creativeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesMediaCreative {
    
    private long source_status_idField;
    
    private string typeField;
    
    private string urlField;
    
    private string media_urlField;
    
    private string media_url_httpsField;
    
    private string display_urlField;
    
    private long id_strField;
    
    private long source_status_id_strField;
    
    private string expanded_urlField;
    
    private usersUserStatusEntitiesMediaCreativeSizes sizesField;
    
    private long idField;
    
    private sbyte endField;
    
    private bool endFieldSpecified;
    
    private sbyte startField;
    
    private bool startFieldSpecified;
    
    /// <remarks/>
    public long source_status_id {
        get {
            return this.source_status_idField;
        }
        set {
            this.source_status_idField = value;
        }
    }
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string media_url {
        get {
            return this.media_urlField;
        }
        set {
            this.media_urlField = value;
        }
    }
    
    /// <remarks/>
    public string media_url_https {
        get {
            return this.media_url_httpsField;
        }
        set {
            this.media_url_httpsField = value;
        }
    }
    
    /// <remarks/>
    public string display_url {
        get {
            return this.display_urlField;
        }
        set {
            this.display_urlField = value;
        }
    }
    
    /// <remarks/>
    public long id_str {
        get {
            return this.id_strField;
        }
        set {
            this.id_strField = value;
        }
    }
    
    /// <remarks/>
    public long source_status_id_str {
        get {
            return this.source_status_id_strField;
        }
        set {
            this.source_status_id_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string expanded_url {
        get {
            return this.expanded_urlField;
        }
        set {
            this.expanded_urlField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusEntitiesMediaCreativeSizes sizes {
        get {
            return this.sizesField;
        }
        set {
            this.sizesField = value;
        }
    }
    
    /// <remarks/>
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endSpecified {
        get {
            return this.endFieldSpecified;
        }
        set {
            this.endFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startSpecified {
        get {
            return this.startFieldSpecified;
        }
        set {
            this.startFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesMediaCreativeSizes {
    
    private usersUserStatusEntitiesMediaCreativeSizesLarge largeField;
    
    private usersUserStatusEntitiesMediaCreativeSizesSmall smallField;
    
    private usersUserStatusEntitiesMediaCreativeSizesMedium mediumField;
    
    private usersUserStatusEntitiesMediaCreativeSizesThumb thumbField;
    
    /// <remarks/>
    public usersUserStatusEntitiesMediaCreativeSizesLarge large {
        get {
            return this.largeField;
        }
        set {
            this.largeField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusEntitiesMediaCreativeSizesSmall small {
        get {
            return this.smallField;
        }
        set {
            this.smallField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusEntitiesMediaCreativeSizesMedium medium {
        get {
            return this.mediumField;
        }
        set {
            this.mediumField = value;
        }
    }
    
    /// <remarks/>
    public usersUserStatusEntitiesMediaCreativeSizesThumb thumb {
        get {
            return this.thumbField;
        }
        set {
            this.thumbField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesMediaCreativeSizesLarge {
    
    private short wField;
    
    private short hField;
    
    private string resizeField;
    
    /// <remarks/>
    public short w {
        get {
            return this.wField;
        }
        set {
            this.wField = value;
        }
    }
    
    /// <remarks/>
    public short h {
        get {
            return this.hField;
        }
        set {
            this.hField = value;
        }
    }
    
    /// <remarks/>
    public string resize {
        get {
            return this.resizeField;
        }
        set {
            this.resizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesMediaCreativeSizesSmall {
    
    private short wField;
    
    private short hField;
    
    private string resizeField;
    
    /// <remarks/>
    public short w {
        get {
            return this.wField;
        }
        set {
            this.wField = value;
        }
    }
    
    /// <remarks/>
    public short h {
        get {
            return this.hField;
        }
        set {
            this.hField = value;
        }
    }
    
    /// <remarks/>
    public string resize {
        get {
            return this.resizeField;
        }
        set {
            this.resizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesMediaCreativeSizesMedium {
    
    private short wField;
    
    private short hField;
    
    private string resizeField;
    
    /// <remarks/>
    public short w {
        get {
            return this.wField;
        }
        set {
            this.wField = value;
        }
    }
    
    /// <remarks/>
    public short h {
        get {
            return this.hField;
        }
        set {
            this.hField = value;
        }
    }
    
    /// <remarks/>
    public string resize {
        get {
            return this.resizeField;
        }
        set {
            this.resizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class usersUserStatusEntitiesMediaCreativeSizesThumb {
    
    private short wField;
    
    private short hField;
    
    private string resizeField;
    
    /// <remarks/>
    public short w {
        get {
            return this.wField;
        }
        set {
            this.wField = value;
        }
    }
    
    /// <remarks/>
    public short h {
        get {
            return this.hField;
        }
        set {
            this.hField = value;
        }
    }
    
    /// <remarks/>
    public string resize {
        get {
            return this.resizeField;
        }
        set {
            this.resizeField = value;
        }
    }
}
